#!/usr/bin/env bash
# This script debugs a Docker container and ensures Apache serves the "Hello Holberton" page.

apt-get update
apt-get install -y apache2
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html

