#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers


# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  charsey_frontend
        bind *:80
        mode http
        default_backend charsey_backend
backend charsey_backend
        balance roundrobin
    server web-01 54.221.165.253:80 check
    server web-02 54.90.134.12:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy/

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
